# Generated by Django 3.2 on 2021-04-07 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewAdmirer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False)),
                ('admirer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_admirer', to=settings.AUTH_USER_MODEL)),
                ('admiring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_admiring', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
