# Generated by Django 3.2 on 2021-04-12 23:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='admirers',
        ),
        migrations.AddField(
            model_name='author',
            name='admiring',
            field=models.ManyToManyField(blank=True, related_name='admirers', to=settings.AUTH_USER_MODEL),
        ),
    ]
