# Generated by Django 3.2 on 2021-04-12 23:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20210412_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='admiring',
        ),
        migrations.AddField(
            model_name='author',
            name='admirers',
            field=models.ManyToManyField(blank=True, related_name='admiring', to=settings.AUTH_USER_MODEL),
        ),
    ]
