# Generated by Django 3.1.7 on 2021-04-07 18:16

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20210407_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='author',
            name='interested_in',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('IGNEOUS', 'Igneous'), ('SEDIMENTARY', 'Sedimentary'), ('METAMORPHIC', 'Metamorphic')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='rock_type',
            field=models.CharField(choices=[('IGNEOUS', 'Igneous'), ('SEDIMENTARY', 'Sedimentary'), ('METAMORPHIC', 'Metamorphic')], max_length=50, null=True),
        ),
    ]
