# Generated by Django 3.1.7 on 2021-04-07 18:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_auto_20210407_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='interested_in',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('IGNEOUS', 'Igneous'), ('SEDIMENTARY', 'Sedimentary'), ('METAMORPHIC', 'Metamorphic')], max_length=35, null=True),
        ),
    ]
